USE codeup_test_db;
DROP TABLE IF EXISTS albums;

CREATE TABLE albums (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	artist VARCHAR(50) NOT NULL,
	name VARCHAR(60) NOT NULL,
	realease_date YEAR NOT NULL,  
	sales FLOAT(11,2) NOT NULL,
	genre VARCHAR(40) NOT NULL,
	PRIMARY KEY (id)
);

FLUSH PRIVILEGES;
SHOW CREATE TABLE albums\G;
