USE codeup_test_db;

TRUNCATE albums;

INSERT INTO albums(artist, name , realease_date , genre , sales)
VALUES
    ('Michael Jackson'           ,'Thriller'                    , 1982, 'Pop, rock, R&B',               42.4),
    ('Pink Floyd'                , 'The Dark Side of the Moon'  , 1973, 'Progressive rock',             22.7),
    ('Whitney Houston'           , 'The Bodyguard'              , 1992, 'Soundtrack/R&B, soul, pop',    27.4),
    ('Meat Loaf'                 , 'Bat Out of Hell'            , 1977, 'Hard rock, progressive rock',  20.6),
    ('Eagles'                    , 'Their Greatest Hits'        , 1976, 'Rock, soft rock, folk rock',   32.2),
    ('AC/DC'                     , 'Back in Black'              , 1980, 'Hard rock' ,                   25.9),
    ('Bee Gees / Various artists', 'Saturday Night Fever'       , 1977, 'Disco'    ,                    19),
    ('Fleetwood Mac'             , 'Rumours'                    , 1977, 'Soft rock' ,                   27.9),
    ('ABBA'                      , 'Gold: Greatest Hits'        , 1992, 'Pop' ,                         28), 
    ('Bon Jovi'                  , 'Slippery When Wet'          , 1986, 'Hard rock'  ,                  28),
    ('Spice Girls'               , 'Spice'                      , 1996, 'Pop',                          28),
    ('Various artists'           , 'Grease: The Original Soundtrack from the Motion Picture', 1978 ,   'Soundtrack',  28),
    ('Britney Spears'            , '...Baby One More Time'      , 1999,  'Pop'                           ,28),
    ('Linkin Park'               ,'Hybrid Theory'                ,2000,    'Nu metal, rap metal, alternative metal'  ,27),
    ('Bob Marley & The Wailers'  , 'Legend: The Best of Bob Marley & The Wailers' ,1984   , 'Reggae'  ,25),
    ('Carole King' ,                'Tapestry'                  ,1971  ,  'Pop', 25),
    ('Madonna' ,                    'Like a Virgin'             ,1984    ,'Pop, dance' , 25),
    ('Madonna' ,                    'True Blue'                 ,1986    ,'Pop' , 25),
    ('Mariah Carey' ,               'Daydream'                  ,1995    ,'Pop, R&B'  ,  25),
    ('Norah Jones' ,                'Come Away with Me'         ,2002    ,'Jazz'  ,  25),
    ('Queen' ,                      'Greatest Hits'             ,1981    ,'Rock'  ,  25),
    ('Simon & Garfunkel' ,          'Bridge over Troubled Water',1970  ,'  Folk rock'  , 25),
    ('U2' ,                         'The Joshua Tree'           ,1987    ,'Rock'   , 25),
    ('Backstreet Boys' ,            'Backstreet\'s Back / Backstreet Boys' ,1997    ,'Pop' ,24),
    ('Backstreet Boys' ,            'Millennium'                ,1999    ,'Pop' ,24),
    ('Ace of Base' ,                'Happy Nation/The Sign'     ,1993    ,'Pop', 23),
    ('TLC' ,                        'CrazySexyCool'             ,1994    ,'R&B, hip hop' ,   23),
    ('Cyndi Lauper' ,               'She\'s So Unusual'         ,1983    ,'New wave, pop rock, synthpop'  ,  22),
    ('Oasis' ,                      '(What\'s the Story) Morning Glory?'   ,1995    ,'Britpop, rock'  , 22),
    ('Bon Jovi' ,                   'Cross Road'                ,1994    ,'Hard rock' ,  21),
    ('Eminem' ,                     'The Marshall Mathers LP'   ,2000    ,'Rap, hip-hop'  ,  21),
    ('Celine Dion' ,                'The Colour of My Love'     ,1993    ,'Pop / Soft rock' ,20),
    ('Avril Lavigne' ,              'Let Go'                    ,2002    ,'Pop rock, alternative rock' , 20),
    ('Boston' ,                     'Boston'                    ,1976    ,'Hard rock' ,  20),
    ('Britney Spears' ,             'Oops!... I Did It Again'   ,2000    ,'Pop', 20),
    ('Def Leppard' ,                'Hysteria'                  ,1987    ,'Pop, Hard rock',  20),
    ('Fei Xiang' ,                  'A Voice on the Ocean'      ,1986    ,'Mandopop' ,   20),
    ('Eric Clapton' ,               'Unplugged'                 ,1992    ,'Acoustic blues, folk rock' ,  20),
    ('Lionel Richie' ,              'Can\'t Slow Down'          ,1983    ,'Pop, R&B, soul' , 20),
    ('Madonna' ,                    'Ray of Light'              ,1998    ,'Pop, Dance, Electronica', 20),
    ('Michael Jackson' ,            'HIStory: Past, Present , and Future, Book I'   ,1995    ,'Pop, rock, R&B' , 20),
    ('Michael Jackson' ,            'Off the Wall'              ,1979    ,'Soul, disco, R&B' ,   20),
    ('Phil Collins' ,               'No Jacket Required'        ,1985    ,'Pop, Rock' ,  20),
    ('Prince & The Revolution' ,    'Purple Rain'               ,1984    ,'Pop, rock, R&B' , 20),
    ('Shania Twain' ,               'The Woman in Me'           ,1995    ,'Country, pop' ,   20),
    ('Supertramp' ,                 'Breakfast in America'      ,1979    ,'Progressive rock, art rock' , 20),
    ('Tina Turner' ,                'Private Dancer'            ,1984    ,'Rock' ,   20),
    ('Toni Braxton' ,               'Secrets'                   ,1996    ,'R&B, Pop' ,   20),
    ('Usher' ,                      'Confessions'               ,2004    ,'R&B' ,20),
    ('Whitney Houston' ,            'Whitney'                   ,1987    ,'Pop, R&B' ,   20),
    ('Green Day' ,                  'Dookie'                    ,1994    ,'Pop-punk, punk rock, alternative rock' ,  20),
    ('Shakira' ,                    'Laundry Service'           ,2001     ,'Pop, Rock' ,  20);

SELECT * FROM albums;
FLUSH PRIVILEGES;
